
const data = 
    [
        "MacBook Air M3",
        "Dell XPS 13",
        "HP Spectre x360",
        "Lenovo ThinkPad X1",
        "Asus ZenBook 14",
        "Acer Swift 3",
        "Microsoft Surface Pro 9",
        "Samsung Galaxy Book4",
        "LG Gram 16",
        "Razer Blade 15",
        "Huawei MateBook X Pro",
        "Google Pixelbook Go",
        "MSI Prestige 14",
        "Alienware m15",
        "Toshiba Dynabook",
        "Sony Vaio SX14",
        "Fujitsu Lifebook U9311",
        "Panasonic Toughbook 55",
        "Chuwi AeroBook",
        "Xiaomi Mi Notebook Pro",
        "Honor MagicBook 14",
        "Realme Book Slim",
        "Infinix INBook X1",
        "Nokia PureBook X14",
        "Vaio E15",
        "Samsung Galaxy S24",
        "Apple iPhone 15",
        "Google Pixel 9",
        "OnePlus 12",
        "Xiaomi Mi 14",
        "Huawei P60",
        "Sony Xperia 1 V",
        "LG Velvet 2",
        "Nokia 10",
        "Asus ROG Phone 7",
        "Lenovo Legion Phone Duel 3",
        "ZTE Axon 30",
        "Oppo Find X6",
        "Vivo X80",
        "Realme GT 3",
        "Honor 50",
        "Motorola Edge 40",
        "TCL 20 Pro",
        "Alcatel 5X",
        "Micromax In Note 2",
        "Lava Agni 2",
        "Infinix Zero 5G",
        "Tecno Phantom X2",
        "Itel Vision 3",
        "Ulefone Armor 12",
        "Doogee S97 Pro",
        "Blackview BV9900",
        "Cubot KingKong 7",
        "Oukitel WP10",
        "Gionee M12",
        "Leagoo M13",
        "Blu G91 Pro",
        "Zopo Speed X",
        "Meizu 18",
        "Sharp Aquos R6",
        "Kyocera DuraForce Ultra",
        "Fairphone 4",
        "Shift6mq",
        "Vsmart Aris Pro",
        "Wiko View5",
        "Symphony Z35",
        "Walton Primo S8",
        "QMobile Phantom P1",
        "Spice F311",
        "Karbonn Titanium S9",
        "Celkon Diamond U 4G",
        "Maxx AX8 Race",
        "Intex Aqua Lions X1",
        "Videocon Krypton3 V50JG",
        "iBall Andi 5G Blink 4G",
        "Lemon Aspire A4",
        "Fly Tornado Slim",
        "Philips Xenium X818",
        "BenQ T55",
        "Siemens SX66",
        "Palm Phone",
        "Essential Phone",
        "Nextbit Robin",
        "YotaPhone 3",
        "Vertu Signature Touch",
        "Cat S62 Pro",
        "Sonim XP8",
        "Energizer Power Max P18K",
        "MobiWire Taima",
        "Archos Diamond Omega",
        "Prestigio Grace X7",
        "Allview X4 Soul Infinity",
        "BQ Aquaris X2",
        "Wileyfox Swift 2X",
        "General Mobile GM 9 Pro",
        "MyPhone Hammer Energy",
        "Kruger&Matz Live 7S",
        "item new",
        "new item",
        "your ass",
        "your butt",
        "new item",
        "Archos Diamond Omega",
        "Prestigio Grace X7",
        "Allview X4 Soul Infinity",
        "BQ Aquaris X2",
        "Wileyfox Swift 2X",
        "General Mobile GM 9 Pro",
        "MyPhone Hammer Energy",
        "Kruger&Matz Live 7S",
        "item new",
        "new item",
        "your ass",
        "your butt",
        "new item",
        "Vsmart Aris Pro",
        "Wiko View5",
        "Symphony Z35",
        "Walton Primo S8",
        "QMobile Phantom P1",
        "Spice F311",
        "Karbonn Titanium S9",
        "Celkon Diamond U 4G",
        "Maxx AX8 Race",
        "Intex Aqua Lions X1",
        "Videocon Krypton3 V50JG",
        "iBall Andi 5G Blink 4G",
        "Lemon Aspire A4",
        "Fly Tornado Slim",
        "Philips Xenium X818",
        "BenQ T55",
        "Siemens SX66",
        "Palm Phone",
        "Essential Phone",
        "Nextbit Robin",
        "YotaPhone 3",
        "Vertu Signature Touch",
        "Cat S62 Pro",
        "Sonim XP8",
        "Energizer Power Max P18K",
        "MobiWire Taima",
        "Archos Diamond Omega",
        "Prestigio Grace X7",
        "Allview X4 Soul Infinity",
        "BQ Aquaris X2",
        "Wileyfox Swift 2X",
        "General Mobile GM 9 Pro",
        "MyPhone Hammer Energy",
        "Kruger&Matz Live 7S",
        "item new",
        "new item",
        "your ass",
        "your butt",
        "new item",
        "Archos Diamond Omega",
        "Prestigio Grace X7",
        "Allview X4 Soul Infinity",
        "BQ Aquaris X2",
        "Wileyfox Swift 2X",
        "General Mobile GM 9 Pro",
        "MyPhone Hammer Energy",
        "Kruger&Matz Live 7S",
        "item new",
        "new item",
        "your ass",
        "your butt",
        "new item",
      ]
      



export default data